server:
  port: 80
spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    main:
      allow-bean-definition-overriding: true
  profiles:
    active: dev
mybatis:
  mapper-locations:
    - classpath:mapper/*.xml
    - classpath*:com/**/mapper/*.xml
  configuration:
    call-setters-on-nulls: true