spring:
  datasource:
    url: jdbc:mysql://localhost:3306/qianya?serverTimezone=GMT%2B8&useSSL=false&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root
    druid:
      initial-size: 5 #连接池初始化大小
      min-idle: 10 #最小空闲连接数
      max-active: 20
  main:
    allow-bean-definition-overriding: true
swagger:
  enable: true